### ISSUE TITLE
action中为空

### ISSUE THREAD

**Issue by gohost-MT** [cy920820/hao4k-signin-action#1]
![image](https://user-images.githubusercontent.com/76913095/106626691-eb3a9080-65b2-11eb-8e90-d4283dd896c8.png)
麻烦问一下，部署后action中为空是什么原因

**Comment by cy920820** [comment]
本项目 action 触发条件有两个，一个是本地 main 分支有 push，另外一个就是每天的定时任务触发，如果二者都未达到，则不触发；
action 触发前需要进行 secrets env 配置，稍后这部分我会更新到 README.md .

**Comment by gohost-MT** [comment]
![image](https://user-images.githubusercontent.com/76913095/106698416-b57dc200-661b-11eb-9393-3a77b8777566.png)
![image](https://user-images.githubusercontent.com/76913095/106698537-f70e6d00-661b-11eb-8939-56eecdc507c6.png)
我把secrets设置好了，但是action中还是空的，是不是哪里设置错了，刚用这个不太会

**Comment by cy920820** [comment]
`hao4k.yml `配置里设置了触发条件：
```yml
on:
  push:
    branches: 
      - main
  schedule:
    - cron: '0 22 * * *'
```

配置完敏感信息后，只需等待 schedule 定时任务到点触发就行了，可以观察明天六点是否正常执行即可

**Comment by gohost-MT** [comment]
修改了一下时间，现在可以了，十分感谢
